### ISSUE TITLE
Need help running the program

### ISSUE THREAD

**Issue by HungerPWAY** [EnnengYang/RepresentationSurgery#1]
I'm not very familiar with the open_clip module, and I encountered such a problem when running the program：

AttributeError: Can't get attribute 'VisualTransformer' on <module 'open_clip.model' from '/home/tangpw/anaconda3/envs/surgery/lib/python3.10/site-packages/open_clip/model.py'>

If you know how to solve this problem, I would be very grateful to you. Looking forward to your reply!

**Comment by EnnengYang** [comment]
Hi, 

Could it be due to the **open_clip version**? In my dev environment, ```open-clip-torch==2.0.2, torch==1.8.1+cu111```, you can try it out.

**Comment by HungerPWAY** [comment]
> Hi,
> 
> Could it be due to the **open_clip version**? In my dev environment, `open-clip-torch==2.0.2, torch==1.8.1+cu111`, you can try it out.

Thank for your reply. It helps me a lot.
