### ISSUE TITLE
Questions about the ratio of dataset and the "online test data"

### ISSUE THREAD

**Issue by HungerPWAY** [EnnengYang/RepresentationSurgery#2]
I didn't find any argument in the code to control the proportion of the test set. I want to know if this code uses 100% of the test set by default. Also, does if i > 0: indicate the use of the "online test data" mode? I would be very grateful if you could help me. Looking forward to your reply!

**Comment by EnnengYang** [comment]
> I didn't find any argument in the code to control the proportion of the test set. I want to know if this code uses 100% of the test set by default. Also, does if i > 0: indicate the use of the "online test data" mode? I would be very grateful if you could help me. Looking forward to your reply!

Hi,

The **online setting** means that only one sample is received at a time, and each sample is passed through the model only once.

The previous code defaults to offline setting. I uploaded a ```.py code``` in the online setting: [main_AdaMerging_with_surgery_online.py](https://github.com/EnnengYang/RepresentationSurgery/blob/main/src/main_AdaMerging_with_surgery_online.py). The log corresponding to the online setting is in [result-ViT-B-32.md](https://github.com/EnnengYang/RepresentationSurgery/blob/main/src/logs/result-ViT-B-32.md).

Best, 
Enneng

**Comment by HungerPWAY** [comment]
Thank your reply! It helps me a lot.
