### ISSUE TITLE
Reproducibility of NLP Tasks

### ISSUE THREAD

**Issue by fskong** [EnnengYang/RepresentationSurgery#3]
Hi,
Thank you for open-sourcing the code, finetuned model, and dataset related to image classification.
I want to reproduce the results for text classification (e.g., Table 6). Could you provide the relevant code, checkpoints, and datasets?
Thank you!

**Comment by EnnengYang** [comment]
Hi,
Thank you for your attention. Relevant resources have been sent to you. 
Thank you.
